remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme

title: Amol Satdive
description: CFD/CAD Portfolio | Product Design | High-Performance Computing

markdown: kramdown
kramdown:
  math_engine: mathjax
